# Generated by Django 3.2.7 on 2021-10-12 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('runtime', models.CharField(max_length=10)),
                ('genre', models.TextField()),
                ('rating', models.FloatField()),
                ('overview', models.TextField()),
                ('meta_score', models.FloatField()),
                ('Director', models.CharField(max_length=20)),
                ('votes', models.BigIntegerField()),
                ('gross', models.BigIntegerField()),
                ('poster_url', models.URLField()),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)])),
            ],
        ),
    ]
